language: objective-c
xcode_workspace: ./Example/VizzleListExample/VizzleListExample.xcworkspace
xcode_scheme: VizzleListExample
cache: cocoapods
podfile: ./Example/VizzleListExample/Podfile
branches:
  only:
  - master
osx_image: xcode7.3
xcode_sdk: iphonesimulator