language: objective-c
osx_image: xcode8.3
before_install:
  - pod setup --silent
  - pod repo update --silent
script: 
  - cd Example
  - pod install
  - xcodebuild -workspace Example.xcworkspace -scheme Example -sdk iphonesimulator