language: objective-c
osx_image: xcode8.3
before_install:
  - pod setup --silent
  - pod repo update --silent
script: 
  - cd Example/VizzleListExample
  - pod install
  - xcodebuild -workspace VizzleListExample.xcworkspace -scheme VizzleListExample -sdk iphonesimulator