# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VizzleListExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
  pod 'VZInspector', '0.1.3'
  pod 'SDWebImage', '3.7.3'
end


